Completion functions and annotations
radian-software/straight.el pull request #874
Opened 2021-10-29 10:36 UTC by roshanshariff

This patch modifies `straight--select-package` and `straight--get-recipe` to use completion functions instead of tables. The completion function allows for
* Setting the completion category to `'straight-recipe`, which is useful for packages like Embark.
* Showing extra metadata when the completion UI supports annotations (see screenshot below, using Vertico).

![image](https://user-images.githubusercontent.com/552952/139419412-a6625eac-14f2-4838-83b4-e0847d16f23a.png)

2021-10-29 19:52 UTC, progfolio requested changes
Thanks for the pull.
I've yet to try it locally, but I've left some general notes/questions from my cursory glance.
I will test this out later tonight and leave more if I notice anything else.

2021-10-29 19:52 UTC, progfolio commented on straight.el
> +    (annotation-function . straight--recipe-annotation-function))
```suggestion
  '((category . straight-recipe)
    (annotation-function . straight--recipe-annotation-function))
```
No need to backquote the list if nothing is being evaluated inside it.

2021-10-29 19:52 UTC, progfolio commented on straight.el
> +  "Information about PACKAGE to be displayed for completion."
```suggestion
  "Return PACKAGE information to be displayed during completion."
```

2021-10-29 19:52 UTC, progfolio commented on straight.el
> +                 (if source (format " %s" source))
```suggestion
                 (when source (format " %s" source))
```
Prefer `when` over `if` if there is no `else` branch.

2021-10-29 19:52 UTC, progfolio commented on straight.el
> +                 (propertize " " 'display '(space :align-to 60))
Should the `:align-to` values be hard coded? What happens when the completion window isn't wide enough to accommodate these values? I assume they will wrap.

2021-10-29 19:52 UTC, progfolio commented on straight.el
> +                   localrepo))))
Similar to above. Instead of using if, we can use `when`:

```emacs-lisp
(when localrepo
  (format " (%s %s)"
          (if (string= localrepo package) "installed" "in")
          package))
```

2021-10-29 19:52 UTC, progfolio commented on straight.el
> +       (complete-with-action action recipes string pred)))))
Does this need to be a `pcase`? At present we're just checking whether or not action is eq to 'metadata.
We could stick with a simple `if` replace it later if we need to support more actions.

2021-10-29 19:52 UTC, progfolio commented on straight.el
> +    (pcase action
Same as above. Is the `pcase` necessary?

2021-10-29 19:52 UTC, progfolio commented on straight.el
> -                      (lambda (_) t)
Is there a reason to remove `completing-read`'s PREDICATE argument in the replaced code?

2021-10-29 21:45 UTC, roshanshariff commented
> I will test this out later tonight and leave more if I notice anything else.

Thanks for the helpful review @progfolio! I'm working on a newer version that fixes the style issues you've pointed out. I'm also improving the annotator function:
* If a package recipe is cached, it shows the source repository
* Otherwise it shows the recipe source (melpa, elpa, etc.)

You might want to wait for the new version before testing it, to save some time :)

2021-10-29 21:46 UTC, roshanshariff commented on straight.el
> -                      (lambda (_) t)
A nil predicate behaves exactly like it is always true, so there's no need to create a lambda in this case.

2021-10-29 21:56 UTC, roshanshariff commented on straight.el
> +                 (propertize " " 'display '(space :align-to 60))
The completion UIs I have seen truncate the annotation if it is too long to fit in one line, which is probably the desired behaviour. It is possibly to dynamically truncate the columns to fit the minibuffer width, but that is unnecessary in this case since it's okay if the right-most information gets hidden. No matter what, the package name itself will always be displayed fully.

I chose to reserve 40 characters for the package name to accommodate almost everything that's currently available. If a package has a longer name it will still be fully visible, but will push the second column to the right. I will adjust the second and third columns with the update I'm working on, but we can't really do much without changes in the Emacs completion-read protocol (that are being discussed, afaik).

2021-10-30 04:43 UTC, roshanshariff commented
I have pushed the new version with better annotations and improved coding style and documentation. Let me know what you think.

The completion for installed packages now looks like this: Note that the remote URL for "helpful" shown here is from my personal fork, not the original recipe. Remote URLs are truncated by Vertico if they don't fit on one line.
![image](https://user-images.githubusercontent.com/552952/139520337-53969804-1170-49c6-a4a6-e1c42178f873.png)

The completion for recipe-related functions looks like this: It now shows the upstream remote for "helpful".
![image](https://user-images.githubusercontent.com/552952/139520431-8c80d412-dcae-4f50-a64c-8fd4bc81acb9.png)

2021-11-01 19:14 UTC, progfolio requested changes
Had the chance to test this locally. Right now the biggest blocker is figuring out the formatting situation. I uploaded a few images in a review comment to give you an idea of what it looks like on my system (with and without helm). If we can get something uniform across completion frameworks, that would be ideal. If not, we could add this feature behind an opt-in defcustom (something like `straight-annotate-recipe-completions`).

Thanks again for your work on this. Let me know if you have any questions.

2021-11-01 19:14 UTC, progfolio commented on straight.el
> +        (straight--with-plist recipe (type)
If we're just binding the recipe's type, it would probably be more efficient to just use `plist-get` directly with the recipe instead of `straight--with-plist` and add the binding to the `let*`. e.g.

```emacs-lisp
(type (plist-get recipe :type)))
```

2021-11-01 19:14 UTC, progfolio commented on straight.el
> +                  (propertize " " 'display '(space :align-to 51)) " %s")
:align-to 51 or 50?

2021-11-01 19:14 UTC, progfolio commented on straight.el
> +               (? ".git") eos)                   ; suffix ".git"
Instead of loading `rx` for this regexp, we can construct it via `concat` and annotate it similar to what you've done:

```emacs-lisp
(concat
 "\\`" ; beginning of string
 "\\(?:[^z-a]*?:\\(?://\\)?\\)?" ; prefix "protocol://"
 "\\([^z-a]*?\\)" ; captured text up to repo extension
 "\\(?:\\.git\\)?" ; ".git" extension
 "\\'" ; end of string
 )
```

2021-11-01 19:29 UTC, roshanshariff commented on straight.el
> +                  (propertize " " 'display '(space :align-to 51)) " %s")
I chose 51 to leave two spaces after the string "installed" because that seemed to look the best :) But I will have to revisit this after we figure out how to do formatting properly.

2021-11-01 19:40 UTC, roshanshariff commented on straight.el
> +          'face 'completions-annotations)))
Ah, I'd expected the annotation to be ignored in the first case, but I'll investigate this further. Maybe the solution is for the annotation-function to be a small string to be displayed alongside the candidate, whereas an additional affixation function can include the longer, column-separated string. It seems like completion UIs prefer an affixation function when available, falling back to annotation function otherwise. And from a quick glance, it looks like Helm only looks at annotations and not affixations.

I'll also have to look into what Helm is doing with the annotation strings on their way to being displayed. Thanks for pointing this out! If there isn't a good solution that works in all cases, I will think about the best way to make this functionality customizable, as you suggested.

2022-09-24 19:30 UTC, progfolio commented
Based off of lack of activity, I'm closing this pull request. If you are still interested in working on this, let me know and we can reopen. Thanks.

2022-09-24 19:30 UTC, closed without merging